name: release

on:
  push:
    tags:
      - '*'

jobs:
  # setup-env:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install build environment
  #       run: |
  #         rustup default nightly
  #         rustup target add x86_64-unknown-linux-musl
  #         rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
  #         sudo apt-get install musl musl-tools musl-dev
  #
  create_release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: release
      uses: actions/create-release@v1
      id: create_release_step
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

  upload_artifact:
    permissions: write-all
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    needs: create_release
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install build environment
      run: |
        rustup default nightly
        rustup target add x86_64-unknown-linux-musl
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
        sudo apt-get install musl musl-tools musl-dev

    - name: Build
      run: cargo build --profile release-with-debug --verbose

    - name: Rename
      run: |
        mv target/x86_64-unknown-linux-musl/release-with-debug/rstream target/x86_64-unknown-linux-musl/release-with-debug/rstream-x86_64-linux
        tar zcf target/x86_64-unknown-linux-musl/release-with-debug/rstream-x86_64-linux.tgz target/x86_64-unknown-linux-musl/release-with-debug/rstream-x86_64-linux

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/x86_64-unknown-linux-musl/release-with-debug/rstream-x86_64-linux.tgz

